### ISSUE TITLE
[Summer 2021] Project B: OpenSource Pysa Tests in Github CI 

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#11]
We would like to implement a basic integration tests verifying that running Pysa on the  deliberately_vulnerable_app (https://github.com/facebook/pyre-check/tree/master/documentation/deliberately_vulnerable_flask_app)  would catch the issue we are expecting. To achieve this we need:

First run Pysa on the [deliberately_vulnerable_app](https://github.com/facebook/pyre-check/tree/master/documentation/deliberately_vulnerable_flask_app) and validate we are catching the right issues. In the previous step we should already be able to test pysa on this project

Then we should create a python script which run pysa on the [deliberately_vulnerable_app](https://github.com/facebook/pyre-check/tree/master/documentation/deliberately_vulnerable_flask_app) and compare the issues detected with an json file containing the list of issue we are expecting to identify. If there is a mismatch an error is returned and the difference between the expected result and the actual result is shown.

Finally we should setup a github new action [here](https://github.com/facebook/pyre-check/tree/master/.github/workflows) which setups the environment and launches the previously created script. We may need to modify how the current setup.sh script works to be able to run it in the github CI

**Comment by abishekvashok** [comment]
Claiming this up!

**Comment by abishekvashok** [comment]
@r0rshark  I am guessing we need to build pyre on github actions each time. So, I did so at: https://github.com/abishekvashok/pyre-check/runs/2884792267

But I am not able to figure out where `taint_models_path` is when you build from the source. Do you know where it might be? I tried ./stubs/taint/ and ./stubs/third-party-taints/ but it throws an exception:
```
ƛ Uncaught exception:

ƛ 

ƛ   Analysis__ClassHierarchy.Untracked("typing.NamedTuple")

ƛ 

ƛ Raised at file "command/analyzeCommand.ml", line 254, characters 6-17

ƛ Called from file "src/command.ml", line 2453, characters 8-238

ƛ Called from file "src/exn.ml", line 111, characters 6-10

ƛ Client exited with error code 1

Error: Process completed with exit code 2.
```

**Comment by abishekvashok** [comment]
Update: digging deeper, I found the taint_models_path is fine.

This error is being caused from somewhere else.

**Comment by r0rshark** [comment]
Yes, I saw similar error before and it was caused by typeshed not being correctly identified. Have you tried using the PYRE_TYPESHED environment variable?
We may try also to use the approach used in the pyre.yml workflow [here](https://github.com/MLH-Fellowship/pyre-check/blob/master/.github/workflows/pyre.yml#L26) to directly get the current pyre nightly version from pip. Does this work?

**Comment by r0rshark** [comment]
Regarding the issue with pyre-check-nightly I am not able to replicate it:
```
python3.8 -m venv ~/.venvs/mlh_test2
source ~/.venvs/mlh_test/bin/activate
pip install Flask
 pip install pyre-check-nightly==0.0.101623930141
cd documentation/deliberately_vulnerable_flask_app
rm ../../.pyre_configuration
pyre init
pyre  --noninteractive analyze --no-verify
```
documentation/deliberately_vulnerable_flask_app/.pyre_configuration: [.pyre_configuration](https://github.com/MLH-Fellowship/pyre-check/files/6701455/pyre_configuration.txt)
The output [lorenzo_log.txt](https://github.com/MLH-Fellowship/pyre-check/files/6701446/lorenzo_log.txt) correctly show the issues

Regarding
> Remember, then the changes made in the pull request regarding pysa will get unchecked. The action would just check if the nightly build detects all issues in the delibrately_vulnerable_flask_app against those defined in true_issues.json. is that fine?
 My idea is to have the `taint_models_path` inside `documentation/deliberately_vulnerable_flask_app/.pyre_configuration` pointing to the `stubs` folder of the repository something like:
 ```
{
  "source_directories": [
    "."
  ],
  "taint_models_path": "../../stubs"
}
```
In this way we will be using the pyre executable from the pyre-check nightly but use the Pysa models defined in the repository. The goal of this test is to validate the Pysa models not the build process of Pyre. What do you think? Does it make sense to you? :)

**Comment by abishekvashok** [comment]
> The goal of this test is to validate the Pysa models not the build process of Pyre. What do you think? Does it make sense to you? :)

Got it, I will try the nightly build again!

**Comment by abishekvashok** [comment]
I tried the nightly build again, but the same output.

Also, this same thing happens in GitHub actions: https://github.com/abishekvashok/pyre-check/runs/2887709253?check_suite_focus=true

**Comment by abishekvashok** [comment]
Quick and happy update! The following configuration works on my local machine!
```
{
 "source_directories": [
   "."
 ],
 "taint_models_path": "../../stubs"
}
```
Implementing it on Github actions and the pull request!

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/pyre-check/commit/97237484e1b6260593196d1bcf94ce0f3733dc8f
