### ISSUE TITLE
[Fall 2021] Step 3: Create GitHub action for Pysa with SARIF output

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#13]
The goal is to document and probably implent a github action which can be used by python projects to integrate with Pysa and run it in the CI pipeline surfacing possible issues as comment in the diff.
In the past we did some collaboration with Zulip so their project can be a good starting point. We can fork https://github.com/zulip/zulip and experiment how this process should look like .
Some work to generate SARIF results was done for surfacing Pyre type checking issues in https://github.com/facebook/pyre-check/pull/427

**Comment by abishekvashok** [comment]
I think I can do this!

> surfacing possible issues as comment in the diff.

Should we show the SARIF results in the action command line itself, or make a bot that comments on the GitHub pull request diff?

**Comment by r0rshark** [comment]
I am not super familiar with SARIF results but I think this should be our way to go

**Comment by abishekvashok** [comment]
Claiming this!

**Comment by abishekvashok** [comment]
Quick update: To publish an action on the GitHub marketplace, we need to have a separate repository for it.

**Comment by abishekvashok** [comment]
@r0rshark done in https://github.com/facebook/pyre-check/pull/440 , please review when you can.

**Comment by abishekvashok** [comment]
@r0rshark here's the PR you requested: https://github.com/abishekvashok/zulip/pull/2 :D

Scroll down to checks section of the PR and see Code Analysis Pysa there (at place where SARIF results show up)
<img width="1440" alt="Screenshot 2021-07-05 at 11 04 17 PM" src="https://user-images.githubusercontent.com/8947010/124504737-b0e55180-dde5-11eb-815b-d5fff64d6e31.png">

Clicking on which should lead you to the issues list. Github is robust enough to show even difference in issues!
<img width="1440" alt="Screenshot 2021-07-05 at 11 04 43 PM" src="https://user-images.githubusercontent.com/8947010/124504812-d3776a80-dde5-11eb-9392-3f9954641188.png">

**Comment by abishekvashok** [comment]
Closed as it's done :)
