### ISSUE TITLE
[Summer 2021] Improve SAPP filtering

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#14]
SAPP (https://github.com/MLH-Fellowship/sapp/) takes the raw results of Pysa and makes them explorable both through a command line interface and a web UI. Currently, SAPP UI is missing the ability to filter by `Source Name`, `Source Kind`, `Sink Name`, and `Sink Kind`. We should add the possibility to filter by those values as well. This work will likely consist of:
1. Adding the filtering support for those values in the python server (https://github.com/MLH-Fellowship/sapp/blob/master/sapp/ui/schema.py#L81)
2. Support the filtering in the ReactJS UI https://github.com/MLH-Fellowship/sapp/blob/master/sapp/ui/frontend/src/Filter.js

**Comment by abishekvashok** [comment]
Fixed via https://github.com/facebook/sapp/pull/23

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/e30857392d6ab2f8e399274d41b7a957678ea511
