### ISSUE TITLE
[Summer 2021] Create Pysa model for flask.Markup

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#15]
Review [flask.Markup](https://tedboy.github.io/flask/generated/generated/flask.Markup.escape.html) to define models for XSS issues. Details on how to create Pysa models in https://pyre-check.org/docs/pysa-basics .
Examples:
- flask.Markup.__init__ may be considered an XSS sink
- flask.Markup.escape: We should add a model to attach a feature  Via[escape_html]

**Comment by abishekvashok** [comment]
This seems fun.. I think I can take this up!

**Comment by abishekvashok** [comment]
So I took a look at the source code, this is what I infer even though I have a poor background in vulnerability detection:
`Markup.__init__` is a sink

`Markup.escape` can be a sanitizer, unless the output of it goes through `Markup.unescape`.

My logic is that the class constructor is called for all functions except escape. Is this the required models?

**Comment by abishekvashok** [comment]
> def markupsafe.Markup.__new__(cls, base: TaintSink[XSS], encoding, errors) : ...
@SkipObscure
def markupsafe._native.escape(s: TaintInTaintOut[Via[escape_html]]): ...

I see this code in third party taints.
This is the markup library used by Jinja2. Going by the same logic, escape should just be a `TaintInTaintOut` with the `via` feature. So I guess that solves the dilemma.

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/pyre-check/commit/aa6590f71a83664bb6b3c271bcfdcbb38b16d33b
