### ISSUE TITLE
[Summer 2021] Implement stubs and models for aiopg

### ISSUE THREAD

**Issue by abishekvashok** [MLH-Fellowship/pyre-check#18]
Implement stubs and models for PostgressSQL library: [aiopg](https://github.com/aio-libs/aiopg)

Information on how to add models to Pysa can be found at: https://pyre-check.org/docs/pysa-basics

This might require addition of stubs: https://pyre-check.org/docs/pysa-tips/#stubs

**Comment by PulkitMishra** [comment]
Not possible without custom stubs. Closing this for now. Can reopen once typeshed supports aiopg.
