### ISSUE TITLE
[Summer 2021] Add models and stubs for psycopg2

### ISSUE THREAD

**Issue by abishekvashok** [MLH-Fellowship/pyre-check#19]
Implement stubs and models for PostgressSQL library: [psycopg2](https://github.com/psycopg/psycopg2)

Information on how to add models to Pysa can be found at: https://pyre-check.org/docs/pysa-basics

This might require addition of stubs: https://pyre-check.org/docs/pysa-tips/#stubs

**Comment by PulkitMishra** [comment]
closed by https://github.com/facebook/pyre-check/pull/455
