### ISSUE TITLE
[Summer 2021] Implement models and stubs for cx_oracle

### ISSUE THREAD

**Issue by abishekvashok** [MLH-Fellowship/pyre-check#22]
Implement stubs and models for Oracle DB library: [cx_oracle](https://github.com/oracle/python-cx_Oracle)

Information on how to add models to Pysa can be found at: https://pyre-check.org/docs/pysa-basics

This might require addition of stubs: https://pyre-check.org/docs/pysa-tips/#stubs

**Comment by PulkitMishra** [comment]
Not possible without custom stubs. Closing this for now. Can reopen once typeshed supports cx_oracle.
