### ISSUE TITLE
[Summer 2021][SAPP] Feature Request - Include file name on trace frames

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#26]
Currently we are only displaying the callable in the trace
![example_trace](https://user-images.githubusercontent.com/3692416/125428040-0717a148-ba5b-4509-9634-fb55eab07ac8.png)
It'd be great if I could also see that file that that trace corresponded to, rather than just the callable

**Comment by abishekvashok** [comment]
I would like to work on this :)

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/8aea64b473f9e44885ec6c802de5fe39924f0236
