### ISSUE TITLE
[Summer 2021][SAPP] Feature Request - Allow users to delete previously imported runs in Web UI

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#27]
Currently, there is no way to delete Runs in Web UI. A user may want to delete a faulty run they imported without having to make a SQL query into their SAPP db.

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/84b90d1691f812de75afbc15194402c639b9418e
