### ISSUE TITLE
[Summer 2021][SAPP] Bug - Users cannot copy any text to clipboard from source code in traces 

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#28]
![image](https://user-images.githubusercontent.com/3692416/125429692-883190f0-72f0-4797-b0ad-40c43aa76523.png)
Attempting to copy + paste the highlighted text above will not work

## Steps to reproduce
Download sapp.db attached to the task
1. pip install fb-sapp
2. git clone https://github.com/stephenbradshaw/breakableflask&& cd breakableflask 
3. sapp server --db-name sapp.db
4. Go to http://localhost:5000
5. Click on any issue and try to copy any source code

**Comment by abishekvashok** [comment]
I know how to do this!

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/b7e87bc571eacc089dc2921d99c7ecba1aa7ee19
