### ISSUE TITLE
[Summer 2021] Coverage Improvements - tornado.web.RequestHandler subclassing

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#29]
A way to define an HTTPRequest handler with tornado framework is to subclass tornado.web.RequestHandler and implement methods like "get", "post" . We should review Tornado RequestHandler API https://www.tornadoweb.org/en/stable/web.html and create a DSL model generator ([documentation](https://www.internalfb.com/intern/staticdocs/pyre/docs/pysa-model-dsl/)) to automatically create User Controlled models .
Given this class:
```python
class WhateverHandler(tornado.web.RequestHandler):

    def get(self, path):
        pass
```
The DSL model generator should generate models like this:
def whatever.WhateverHandler.get(path: TaintSource[UserControlled]): ...

**Comment by abishekvashok** [comment]
Claiming this issue!

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/pyre-check/commit/5108db9ab7f8006a955a6b26d9564b7562c2c1b6
