### ISSUE TITLE
[Summer 2021] SAPP Feature Request - Create easier access to selecting saved filters in Web UI

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#30]
The current workflow to loading a saved filter on SAPP Web UI is to:
- sapp --database-name starter.db server
- Click the Filter button
- Click the saved filter field
- Click the name of the saved filter you want to apply
- Click the Apply button and wait for the page to refresh
One idea to make it easier to select filters is to create a sidebar with a list of saved filters and clicking on one saved filter applies the filter and refreshes the page

**Comment by abishekvashok** [comment]
Claiming this!

**Comment by abishekvashok** [comment]
@r0rshark I tried the sidebar but it looked kinda ugly. So I added a popup https://github.com/facebook/sapp/pull/27 , let me know if you really want the sidebar, and possibly move filter names outside of the autocompletation field?

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/22843c34b3e0036230af5a6cd96e869c75c86948
