### ISSUE TITLE
[Summer 2021] [SAPP] Feature Request - Reduce number of interactions in Web UI required to re-save a filter 

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#32]
## Scenario
Suppose a user has a saved filter named Test Filter 1 that filters for Code == 5008, but the user wants Test Filter 1 to filter for Code == 5008 and Code == 5012.

## Expected workflow:
The following is the flow a user would expect to accomplish the scenario above:
Ensure you have a Pysa run in a SAPP db that contains issues with code 5008 and 5012
- sapp --database-name test.db server
- Click the Filter button
- Click the saved filter field
- Click Test Filter 1
- Add 5012 to Codes field
- Click the menu button and click Save. Notice on this step that the Save button is grayed out and the user isn't able to save the edited filter.

## Actual workflow:
But the current flow to accomplish the scenario above:
Ensure you have a Pysa run in a SAPP db that contains issues with code 5008 and 5012
- sapp --database-name test.db server
- Click the Filter button
- Click the saved filter field
- Click Test Filter 1
- Remember all the field values populated or screenshot the field values populated
- Click the Clear button
- Click the Filter button
- Fill in the fields from your memory or a screenshot from Step 5
- Add the additional things you wanted to filter for - Add 5012 to Codes field
- Click the menu button and click Save
- Type in the name of the filter you want to save as - Test Filter 1

**Comment by abishekvashok** [comment]
I would like to work on it. But this touches functionality in https://github.com/facebook/sapp/pull/27

I am also not liking the position of save and load, what do you feel we move them outside to the form itself and then, implement collapasables and add update filter and save filter options there near clear and apply buttons?

**Comment by abishekvashok** [comment]
I though it would be less work if https://github.com/facebook/sapp/pull/27 is merged, but it's taking time as it has evolved a lot, thereby, taking this up. I can rework in order of merge if needed :)

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/183bff992d5e4217f4246a67a1fe42025dd5db91
