### ISSUE TITLE
[Summer 2021] [SAPP] Bug - Previously applied filter in Web UI to Run `n` persists across accesses to different Runs

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#33]
## Scenario
Suppose a user has a saved filter named Test Filter 1 that only filters for issues with code 5003

## Steps to reproduce
Ensure you have two Pysa runs in a SAPP db that both contains issues with code 5003
- sapp --database-name test.db server and go to http://localhost:5000/
- Click Issues for Run 1
- Click the Filter button
- Apply Test Filter 1 and notice only issues with code 5003 are shown
- Go to http://localhost:5000/runs
- Click Issues for Run 2
- Notice the list only displays issues with code 5003 and Test Filter 1 is still applied
The expected behavior after step 5 and 6 is to remove  Test Filter 1 and display the full list of issues in Run 2. Same behaviour should apply when loading the same Run again basically we want to remove every filters when a Run is loaded

**Comment by abishekvashok** [comment]
I got this!

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/080b52013fe2c68d49382c1494975f702c1e251f
