### ISSUE TITLE
[Summer 2021] Feature Request - Reduce number of interactions in Web UI to stop filtering and show all issues

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#34]
## Scenario
Assume a user currently has Test Filter 1 applied on their list of issues and the user wants to go back to viewing all the issues for the Pysa run they are currently reviewing

## Expected workflow:
The following is the flow a user would expect to accomplish the scenario above:
- Click some Clear button visible next to the Filter button or whatever alternative solution we come up with
- They can now view all issues

## Actual workflow:
But the current flow to accomplish the scenario above:
- Click the Filter button
- Click the Clear button
- Click the Apply button

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/d7698320276f5b696f145a202cfc012c210ff8e4
