### ISSUE TITLE
[Summer 2021] SAPP Feature Request - Support edit status code in Issue UI 

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#35]
`Issue` model has a [status](https://github.com/facebook/sapp/blob/master/sapp/models.py#L586) field which defaults to `uncategorized` we should support updating it from the UI through a dropdown showing the supported [Statuses](https://github.com/facebook/sapp/blob/master/sapp/models.py#L506)

**Comment by abishekvashok** [comment]
Claiming this :)

**Comment by abishekvashok** [comment]
@r0rshark what are your thoughts on adding filter support as well?

**Comment by r0rshark** [comment]
Yes that would be ideal

**Comment by abishekvashok** [comment]
@r0rshark sorry it took a while, but yeah, did it: https://github.com/facebook/sapp/pull/30

**Comment by abishekvashok** [comment]
Closed via `https://github.com/facebook/sapp/commit/c59f5833ede65c5f6b7ddb66a2dfade686313a06`
