### ISSUE TITLE
[Summer 2021] SAPP support filter export function

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#39]
Currently there is no way to easily export and share a filter from the UI.
We have a functionality to import the filter in JSON format in the DB  https://pyre-check.org/docs/pysa-quickstart#initial-configuration we should support exporting the filter in the same format

**Comment by abishekvashok** [comment]
Fixed via https://github.com/facebook/sapp/commit/2602f618ff6d1025574b4a3580ae835017f2717d
