### ISSUE TITLE
[Summer 2021] Add CI checks with flake8, black and usort in the SAPP repo

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#40]
As title add flake8, black and usort that we already have in pyre check in the SAPP repo as well

**Comment by abishekvashok** [comment]
I got this!

**Comment by abishekvashok** [comment]
@r0rshark I added flake8, usort, and black in the PR. But since sapp has react as well, I was wondering whether you guys internally use a linter to style check/format those files.

**Comment by r0rshark** [comment]
Great! I didn't find internal suggestions for the Opensource but I see some usage of eslint https://github.com/facebookresearch/ParlAI/blob/master/.github/workflows/lint.yml#L109 I am not very familiar with JS linting but we can give it a try and see how many issues we would need to deal with and the value of them :)

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/44ef0708c5434287404428f8491471c001541d61
