### ISSUE TITLE
[Summer 2021] Improve SAPP UI development

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#41]
Currently to test UI changes in SAPP we need to run everytime https://github.com/facebook/sapp#development-environment-setup
```
(sapp) $ cd sapp/ui/frontend && npm run-script build
(sapp) $ python3 -m sapp.cli server --debug
```
It would be nice if we can do this without having to run `npm run-script build` every time.
We can achieve this by using 
```
python3 -m sapp.cli server --debug -> serve the graphql api on localhost:5000
cd sapp/ui/frontend && npm start -> serve react app on localhost:3000

```
To make this work:
1. When we are in development mode we need to change the URL used by Apollo in ReactJS from /graphql to localhost:5000/graphql
2. When we are in development mode (DEBUG environment variable) we can allows CORS request coming from localhost:3000 (react app started with npm start)

To define development specific config we can use environment variables in react https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by abishekvashok** [comment]
I got this!

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/f36553cf0132aa4537f3ecce8d146ce7a55fded8
