### ISSUE TITLE
[Summer 2021] Add coverage for flask.request.json

### ISSUE THREAD

**Issue by abishekvashok** [MLH-Fellowship/pyre-check#45]
Investigate if it is possible to add coverage for flask.request.json. The get_json() function is covered, this should be a one-liner but the stubs don't have the request attribute so this might get tricky.

**Comment by abishekvashok** [comment]
Can't detect the json attribute as the stubs in typeshed doesn't have that attribute. From https://tedboy.github.io/flask/_modules/flask/wrappers.html#Request.json I can see that it is depreciated.  I guess that's why it's not in the typeshed stubs. I am getting:
```
Undefined attribute [16]: Module `requests` has no attribute `json`.
```

**Comment by r0rshark** [comment]
Make sense! I think we can skip this given that;s not valid anymore

**Comment by abishekvashok** [comment]
Yep, closing this then!
