### ISSUE TITLE
[Summer 2021] SAPP Cli add support for AddFeature Pipeline

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#47]
We want to support in SAPP Cli the capability to automatically add a specific features to all the imported issues.
This can be done by creating a new "pipeline" [here](https://github.com/facebook/sapp/tree/main/sapp/pipeline) e.g AddFeatures which process all the issues and add .
We can then add a cli option to the analyze command [here](https://github.com/facebook/sapp/blob/main/sapp/cli_lib.py#L152) to conditionally add the AddFeatures pipeline step adding the features specified in the command line

**Comment by abishekvashok** [comment]
I can do this :)

**Comment by abishekvashok** [comment]
I can still see https://github.com/facebook/sapp/pull/39 is open. @r0rshark was this closed intentionally? :)
