### ISSUE TITLE
[Summer 2021] Create Tests for the SAPP UI Frontend

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#48]
The SAPP UI frontend is getting bigger we should start implementing some test. Based on https://reactjs.org/docs/testing.html a good framework is JEST we can try to set it up and define some tests to cover some of the critical parts like issue rendering and filtering

**Comment by abishekvashok** [comment]
I can do this :)

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/sapp/commit/89aa992765512bb3eac4e1f47eac2fa55cc22791
