### ISSUE TITLE
[Summer 2021] Small bug fix and feature

### ISSUE THREAD

**Issue by r0rshark** [MLH-Fellowship/pyre-check#49]
1. As in picture below there seem to be a rendering bug on the status dropdown when viewing an issue. (URL /run/1/issue/1)
<img width="367" alt="Screenshot 2021-08-12 at 11 51 17" src="https://user-images.githubusercontent.com/3692416/129185053-e63c42e1-d919-4717-9971-56dc18f287bd.png">

2. In the sapp.db we are storing the first_seen time of the issue but we are not surfacing it in the UI. Let's add it to the issue detail and lit
```
sqlite> select * from issues LIMIT 2;
id|handle|code|first_seen|status|task_number|triage_history_fbid|feedback_fbid
1|tools.run-dev.BaseHandler.prepare:27|27|62:6302:402d4dcf54cfdb36|6302|2021-07-23 21:57:00.537787|uncategorized|||
2|zerver.webhooks.yo.view.api_yo_app_webhook:10|77|81:5008:42ddca5d9b5606b5|5008|2021-07-23 21:57:00.537787|uncategorized|||
```

**Comment by abishekvashok** [comment]
I got this :)

**Comment by abishekvashok** [comment]
@r0rshark 1. is not reproducible when I checkout the code from the main branch in the repository. But I can see the ellipse and truncation on `uncategorised` when I select `do not care`.
<img width="1440" alt="Screenshot 2021-08-12 at 4 38 42 PM" src="https://user-images.githubusercontent.com/8947010/129187051-53b03814-9996-458b-bdb1-834c47048bda.png">

We could in any case get it working with this PR, that adds minimum width. If we have time/resource to dig deeper I will be happy to check on the response you got from the server (status is null here? Or was this set via editing the Dom?) Anyway, here's: https://github.com/facebook/sapp/pull/42

**Comment by abishekvashok** [comment]
For the second one, do we need a filter? If so, what should be the filter criteria? Date alone or date and time?

**Comment by abishekvashok** [comment]
I pushed in https://github.com/facebook/sapp/pull/43 for 2. But if we like a filter, I will be more than happy to push implement it :)

**Comment by abishekvashok** [comment]
Solved second one via https://github.com/facebook/sapp/commit/3b64fc964c951a0fca4dc6278dc1a76cb55d9206
