### ISSUE TITLE
Step 4: Syntax Highlighting

### ISSUE THREAD

**Issue by gbleaney** [MLH-Fellowship/pyre-check#6]
The goal here is to have the plugin turn on syntax highlighting for the two kinds of files relavent to Pysa: `taint.config` and `*.pysa` files.

[Here are the VSCode docs](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#contributing-a-basic-grammar) on syntax highlighting.

For `.pysa` files, the highlighting should look like exactly what you get in a `.py` file. As a start, see if we can just get a Python syntax highlighter to passably highlight the file. As a stretch goal, see if you can modify the Python syntax highlighter into treating the fully qualified function name the same as a normal unqualified function name. As a REAL stretch goal, see if you can treat [DSL code](https://pyre-check.org/docs/pysa-model-dsl) in `.pysa` files as an [embedded language](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages) and highlight it differently

`taint.config` files are just JSON files, so all you need to do is apply a JSON highlighter to the file.

**Comment by gracewgao** [comment]
Thanks, I'll give this a try and see what I can do!
