### ISSUE TITLE
[Fall 2021] Step 3: Add Python and third-party library version information to our Pysa models

### ISSUE THREAD

**Issue by onionymous** [MLH-Fellowship/pyre-check#83]
Pysa models are closely related to the Python code they're modeling. They look very similar to type stubs, and rely on annotating specific function names, parameters, or other values. Unfortunately, things like function names and parameters are subject to change across library versions, whether this is the standard Python library, or a third party library. 

Right now there is no information about what Python version or what library version our models are for. This means it can be very confusing when someone installs Pysa and is running a different version of Python to the ones our models are for, since we can see.

The goal of this project is to support annotating Pysa models with a special type of comment, i.e. shebang-style annotations. Similar to how Python and library versions are specified in requirements.txt files, we want to support the same syntax in Pysa model files. Please see https://www.python.org/dev/peps/pep-0508/ and https://www.python.org/dev/peps/pep-0440/#version-specifiers for how version information should be specified.

1. A global version annotation at the top of a .pysa file will apply to all models in that file.
```
#! python == 3.8 
def foo.bar(x: TaintSink[Test]): ...
def foo.baz(y: TaintSink[Test]): ...
```
2. Inline annotations can override the global version annotation:
```
#! python == 3.8 
def foo.bar(x: TaintSink[Test]): ...  #! python >= 3.7, foo >= 1.1
def foo.baz(y: TaintSink[Test]): ...
```
3. Finally, we want to have some pre-processing step before we run Pysa that checks the user's currently Python environment and installed modules, and skips or disables models if there is a version mismatch or the version requirement is not satisfied.

#### Additional follow up tasks
1. Add version annotations for all of our current models.
2. Add documentation for the new version annotation features

**Comment by gbleaney** [comment]
> We could support if sys.version_info == (3, 8): statements in .pysa files. This is what type stubs (.pyi) file use to solve this problem.

Strongly in favour of this one. I love that our model files are basically identical to stub files (in fact, we used to call them stub files until it got too confusing). Continuing to share as many conventions as possible with stub files reduces the cognitive burden of features by relying on a pattern (some) people already know

**Comment by arthaud** [comment]
> Agree completely - this would be really great. Is this related to our other goal of 'support arbitrary Python in .pysa files' or can it be standalone?

I would make it standalone. That seems higher priority than arbitrary python in .pysa files.
