### ISSUE TITLE
[Fall 2021] Step 3: Clean up unclassified errors in the model parser

### ISSUE THREAD

**Issue by onionymous** [MLH-Fellowship/pyre-check#85]
In our model parser: https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/modelParser.ml

we still have a lot of uses of `UnclassifiedError` (https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/modelParser.ml#L214) which is a relic from before we had our new, well-typed errors. 

The goal of this project is just to clean up all those cases and replace them with more specific, well-typed errors, adding more variants to `ModelVerificationError` (https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/modelVerificationError.ml) as necessary.

Please also update and add existing unit tests and integration as necessary to match the new error messages.

**Comment by abishekvashok** [comment]
Closed via https://github.com/facebook/pyre-check/commit/848906a7fb9285cf01b5d8451bb4a2c87155fb29
