### ISSUE TITLE
[Fall 2021] Step 3: Add an `AllOf` constraint to the Pysa DSL

### ISSUE THREAD

**Issue by onionymous** [MLH-Fellowship/pyre-check#86]
### Overview
The [Pysa DSL](https://pyre-check.org/docs/pysa-model-dsl) is a domain-specific language used to generate models in bulk without having to individually specify them using certain query conditions.

The goal of this task is to support an `AllOf` constraint in the `where` clause. For example:
```
ModelQuery(
 find = "methods",
 where = [
   AnyOf(
     AllOf(
        parent.extends("a.b"),
        parent.matches("Foo"),
     ),
     AllOf(
        parent.extends("c.d"),
        parent.matches("Bar")
     )
    )
  ],
 model = [
   Returns(TaintSource[UserControlled]),
 ]
)
```

This query would let us find methods on classes where (the class extends `a.b` AND the class name matches `Foo`) OR (the class extends `c.d` AND the class name matches `Bar`), and model all of those methods as returning `TaintSource[UserControlled]`.

### Implementation
This should be implemented in very similar way to the existing [AnyOf](https://pyre-check.org/docs/pysa-model-dsl#anyof-clauses) constraint. You can see how that is implemented in the parser and model query files for reference.

There are two parts to this, adding the new variant and logic in [modelQuery.ml](https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/modelQuery/modelQuery.ml) logic and supporting the syntax in the [modelParser.ml](https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/modelParser.ml).

### Testing
Please test extensively! I would recommend writing new unit tests in:
* [modelQueryTest.ml](https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/modelQuery/test/modelQueryTest.ml)
* [modelTest.ml](https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/test/modelTest.ml)

As well as integration tests under https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/test/integration/:
* [model_query.py.pysa](https://github.com/facebook/pyre-check/blob/main/source/interprocedural_analyses/taint/test/integration/model_query.py.pysa)

Please note that with the integration test environment, the test sources have the name foo.py, the models for that file should go in foo.py.pysa, and the taint configuration should go in foo.py.config. You can look at existing tests for reference. When the integration test is run, foo.py.cg, foo.py.overrides and foo.py.models will be automatically generated and will be considered the 'expected output' to compare runs against.

### Documentation

Please also update the [Pysa DSL documentation](https://github.com/facebook/pyre-check/blob/main/documentation/website/docs/pysa_model_dsl.md) with information about the new constraint when you are done implementing the feature.

**Comment by abishekvashok** [comment]
I think I know how to do this XD
